'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace NVCMS.Modules.Banner
    
    Partial Public Class EditTemplate
        
        '''<summary>
        '''Title control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Title As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtFilePath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtFilePath As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtcode As Global.System.Web.UI.HtmlControls.HtmlTextArea
        
        '''<summary>
        '''hdf_textcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdf_textcode As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''lbtUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtUpdate As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lbtCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtCancel As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lbtDel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtDel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
