'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace NVCMS.Modules.HeThong

    Partial Public Class menuadmin

        '''<summary>
        '''drlMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drlMenu As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lnkUpdateEditParams control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkUpdateEditParams As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCancelEditParams control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkCancelEditParams As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''drdLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drdLink As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''chkLinkPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkLinkPopup As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtUrl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUrl As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtNodeName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNodeName As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chkUnderline control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUnderline As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

        '''<summary>
        '''txtBackground control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtBackground As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''txtParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtParam As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''chkApplyToAllChildren control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkApplyToAllChildren As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''chkGrantAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkGrantAll As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trGroups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trGroups As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''cboRoleGroups control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboRoleGroups As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''trRoleGrids control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trRoleGrids As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''chkChooseThisPermission control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkChooseThisPermission As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''trUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trUser As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''txtUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUser As Global.System.Web.UI.HtmlControls.HtmlInputText

        '''<summary>
        '''lblErrMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblErrMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdAddUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddUser As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''trUserGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trUserGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lnkRemoveUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnkRemoveUser As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''Label7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
