'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FilesSettings
    
    '''<summary>
    '''uptpanefils control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uptpanefils As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''txtSXCTVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSXCTVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSXCTPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSXCTPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnhLuuTruVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnhLuuTruVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAnhLuuTruPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnhLuuTruPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFlashVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFlashVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFlashPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFlashPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMediaPathVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMediaPathVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMediaPathPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMediaPathPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDocumentLuuTruVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocumentLuuTruVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDocumentLuuTruPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDocumentLuuTruPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMediaLuuTruVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMediaLuuTruVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMediaLuuTruPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMediaLuuTruPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBaiHatVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBaiHatVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBaiHatPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBaiHatPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSanPhamTruVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSanPhamTruVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSanPhaTruPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSanPhaTruPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVideoVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVideoVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtVideoPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVideoPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBackupPathVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBackupPathVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtBackupPathPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBackupPathPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAlertRequestDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlertRequestDuration As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtAutoSaveRequestDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAutoSaveRequestDuration As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDataRequestDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDataRequestDuration As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbtUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUpdate As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtCancelTop control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtCancelTop As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''UpdateProgress1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdateProgress1 As Global.System.Web.UI.UpdateProgress
    
    '''<summary>
    '''txtFTPVirtual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFTPVirtual As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtFTPPhysical control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFTPPhysical As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtDalet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDalet As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkDalet2XML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDalet2XML As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtNetia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNetia As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''chkNetia2XML control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNetia2XML As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtMultiMediaCopyPath1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMultiMediaCopyPath1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMultiMediaCopyPath2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMultiMediaCopyPath2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMultiMediaCopyPath3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMultiMediaCopyPath3 As Global.System.Web.UI.WebControls.TextBox
End Class
