Imports DotNetNuke.Common.Utilities
Namespace NVCMS.Modules.School

    Public Class Admission4YearController
        Public Function Admis_4Year_GetByTruongID(ByVal TruongId As Integer) As Admission4YearInfo
            Return CType(CBO.FillObject(Of Admission4YearInfo)(DataProvider.Instance.Admis_4Year_GetByTruongID(TruongId), True), Admission4YearInfo)
        End Function
        '==========================================================
        'Public Function Admis_4Year_Insert(ByVal FallESL As DateTime, ByVal FallUnder As DateTime, ByVal FallGrad As DateTime, ByVal FallAss As DateTime, ByVal WinterESL As DateTime, ByVal WinterUnder As DateTime, ByVal WinterGrad As DateTime, ByVal WinterAss As DateTime, ByVal SpringESL As DateTime, ByVal SpringUnder As DateTime, ByVal SpringGrad As DateTime, ByVal SpringAss As DateTime, ByVal SummerESL As DateTime, ByVal SummerUnder As DateTime, ByVal SummerGrad As DateTime, ByVal SummerAss As DateTime, ByVal RollingESL As Boolean, ByVal RollingUnder As Boolean, ByVal RollingGrad As Boolean, ByVal RollingAss As Boolean, ByVal CreatedDate As DateTime, ByVal UserId As Integer, ByVal Portalid As Integer) As Integer
        '    Return CType(DataProvider.Instance.Admis_4Year_Insert(FallESL, FallUnder, FallGrad, FallAss, WinterESL, WinterUnder, WinterGrad, WinterAss, SpringESL, SpringUnder, SpringGrad, SpringAss, SummerESL, SummerUnder, SummerGrad, SummerAss, RollingESL, RollingUnder, RollingGrad, RollingAss, CreatedDate, UserId, Portalid), Integer)
        'End Function
        ''------------------------------------------'
        'Public Sub Admis_4Year_Updatetestrequirement(ByVal id As Integer, ByVal TestRequirementsTOEFLESL As Boolean, ByVal TestRequirementsTOEFLUnder As Boolean, ByVal TestRequirementsTOEFLGrad As Boolean, ByVal TestRequirementsSATUnder As Boolean, ByVal TestRequirementsGMATGrad As Boolean, ByVal CreatedDate As DateTime, ByVal UserId As Integer, ByVal Portalid As Integer)
        '    DataProvider.Instance.Admis_4Year_Updatetestrequirement(id, TestRequirementsTOEFLESL, TestRequirementsTOEFLUnder, TestRequirementsTOEFLGrad, TestRequirementsSATUnder, TestRequirementsGMATGrad, CreatedDate, UserId, Portalid)
        'End Sub
        ''------------------------------------------'
        'Public Sub Admis_4Year_UpdateApplicationdeadline(ByVal id As Integer, ByVal FallESL As DateTime, ByVal FallUnder As DateTime, ByVal FallGrad As DateTime, ByVal FallAss As DateTime, ByVal WinterESL As DateTime, ByVal WinterUnder As DateTime, ByVal WinterGrad As DateTime, ByVal WinterAss As DateTime, ByVal SpringESL As DateTime, ByVal SpringUnder As DateTime, ByVal SpringGrad As DateTime, ByVal SpringAss As DateTime, ByVal SummerESL As DateTime, ByVal SummerUnder As DateTime, ByVal SummerGrad As DateTime, ByVal SummerAss As DateTime, ByVal RollingESL As Boolean, ByVal RollingUnder As Boolean, ByVal RollingGrad As Boolean, ByVal RollingAss As Boolean, ByVal CreatedDate As DateTime, ByVal UserId As Integer, ByVal Portalid As Integer)
        '    DataProvider.Instance.Admis_4Year_UpdateApplicationdeadline(id, FallESL, FallUnder, FallGrad, FallAss, WinterESL, WinterUnder, WinterGrad, WinterAss, SpringESL, SpringUnder, SpringGrad, SpringAss, SummerESL, SummerUnder, SummerGrad, SummerAss, RollingESL, RollingUnder, RollingGrad, RollingAss, CreatedDate, UserId, Portalid)
        'End Sub
        ''------------------------------------------'
        'Public Sub Admis_4Year_UpdateEstimatedCost(ByVal id As Integer, ByVal COSTuitionfeeESL As Integer, ByVal COSTuitionfeeUnder As Integer, ByVal COSTuitionfeeGrad As Integer, ByVal COSTuitionfeeAss As Integer, ByVal COSBooksuppliesESL As Integer, ByVal COSBooksuppliesUnder As Integer, ByVal COSBooksuppliesGrad As Integer, ByVal COSBooksuppliesAss As Integer, ByVal COSHealthESL As Integer, ByVal COSHealthUnder As Integer, ByVal COSHealthGrad As Integer, ByVal COSHealthAss As Integer, ByVal COSRoomESL As Integer, ByVal COSRoomUnder As Integer, ByVal COSRoomGrad As Integer, ByVal COSRoomAss As Integer, ByVal COSTransportESL As Integer, ByVal COSTransportUnder As Integer, ByVal COSTransportGrad As Integer, ByVal COSTransportAss As Integer, ByVal COSOtherESL As Integer, ByVal COSOtherUnder As Integer, ByVal COSOtherGrad As Integer, ByVal COSOtherAss As Integer, ByVal CreatedDate As DateTime, ByVal UserId As Integer, ByVal Portalid As Integer)
        '    DataProvider.Instance.Admis_4Year_UpdateEstimatedCost(id, COSTuitionfeeESL, COSTuitionfeeUnder, COSTuitionfeeGrad, COSTuitionfeeAss, COSBooksuppliesESL, COSBooksuppliesUnder, COSBooksuppliesGrad, COSBooksuppliesAss, COSHealthESL, COSHealthUnder, COSHealthGrad, COSHealthAss, COSRoomESL, COSRoomUnder, COSRoomGrad, COSRoomAss, COSTransportESL, COSTransportUnder, COSTransportGrad, COSTransportAss, COSOtherESL, COSOtherUnder, COSOtherGrad, COSOtherAss, CreatedDate, UserId, Portalid)
        'End Sub
        ''------------------------------------------'
        'Public Sub Admis_4Year_UpdateHousing(ByVal id As Integer, ByVal HousingOptionOncampusESL As Boolean, ByVal HousingOptionOncampusUnder As Boolean, ByVal HousingOptionOncampusGrad As Boolean, ByVal HousingOptionOncampusAss As Boolean, ByVal HousingOptionHostFamilyESL As Boolean, ByVal HousingOptionHostFamilyUnder As Boolean, ByVal HousingOptionHostFamilyGrad As Boolean, ByVal HousingOptionHostFamilyAss As Boolean, ByVal HousingOptionApertmentESL As Boolean, ByVal HousingOptionApertmentUnder As Boolean, ByVal HousingOptionApertmentGrad As Boolean, ByVal HousingOptionApertmentAss As Boolean, ByVal HousingOptionHousingESL As Boolean, ByVal HousingOptionHousingUnder As Boolean, ByVal HousingOptionHousingGrad As Boolean, ByVal HousingOptionHousingAss As Boolean, ByVal HousingOptionOtherESL As String, ByVal HousingOptionOtherESLVN As String, ByVal HousingOptionOtherUnder As String, ByVal HousingOptionOtherUnderVN As String, ByVal HousingOptionOtherGrad As String, ByVal HousingOptionOtherGradVN As String, ByVal HousingOptionOtherAss As String, ByVal HousingOptionOtherAssVN As String, ByVal HousingOptionRequirecampus As Boolean, ByVal CreatedDate As DateTime, ByVal UserId As Integer, ByVal Portalid As Integer)
        '    DataProvider.Instance.Admis_4Year_UpdateHousing(id, HousingOptionOncampusESL, HousingOptionOncampusUnder, HousingOptionOncampusGrad, HousingOptionOncampusAss, HousingOptionHostFamilyESL, HousingOptionHostFamilyUnder, HousingOptionHostFamilyGrad, HousingOptionHostFamilyAss, HousingOptionApertmentESL, HousingOptionApertmentUnder, HousingOptionApertmentGrad, HousingOptionApertmentAss, HousingOptionHousingESL, HousingOptionHousingUnder, HousingOptionHousingGrad, HousingOptionHousingAss, HousingOptionOtherESL, HousingOptionOtherESLVN, HousingOptionOtherUnder, HousingOptionOtherUnderVN, HousingOptionOtherGrad, HousingOptionOtherGradVN, HousingOptionOtherAss, HousingOptionOtherAssVN, HousingOptionRequirecampus, CreatedDate, UserId, Portalid)
        'End Sub
        ''------------------------------------------'
        'Public Sub Admis_4Year_UpdateIntensiveEnglish(ByVal id As Integer, ByVal IntensiveEnglish As Boolean, HighSchoolCompletion As Boolean, ByVal FSESL As String, ByVal FSUnder As String, ByVal FSGrad As String, FSAcademic As String, ByVal MostMajor As String, Top5TransferSchools As String, ByVal OnCampus As Boolean, ByVal GraduationRate As String, ByVal EmploymentRateAfterGraduation As String, ByVal CreatedDate As DateTime, ByVal UserId As Integer, ByVal Portalid As Integer)
        '    DataProvider.Instance.Admis_4Year_UpdateIntensiveEnglish(id, IntensiveEnglish, HighSchoolCompletion, FSESL, FSUnder, FSGrad, FSAcademic, MostMajor, Top5TransferSchools, OnCampus, GraduationRate, EmploymentRateAfterGraduation, CreatedDate, UserId, Portalid)
        'End Sub
        ''------------------------------------------'
        'Public Sub Admis_4Year_UpdateNumberofStudents(ByVal id As Integer, ByVal NOSTotalESL As Integer, ByVal NOSTotalUnder As Integer, ByVal NOSTotalGrad As Integer, ByVal NOSTotalAss As Integer, ByVal NOSInternationalESL As Integer, ByVal NOSInternationalUnder As Integer, ByVal NOSInternationalGrad As Integer, ByVal NOSInternationalAss As Integer, ByVal NOSVNESL As Integer, ByVal NOSVNUnder As Integer, ByVal NOSVNGrad As Integer, ByVal NOSVNAss As Integer, ByVal NOSStudentFacultyRatioESL As String, ByVal NOSStudentFacultyRatioUnder As String, ByVal NOSStudentFacultyRatioGrad As String, ByVal NOSStudentFacultyRatioAss As String, ByVal CreatedDate As DateTime, ByVal UserId As Integer, ByVal Portalid As Integer)
        '    DataProvider.Instance.Admis_4Year_UpdateNumberofStudents(id, NOSTotalESL, NOSTotalUnder, NOSTotalGrad, NOSTotalAss, NOSInternationalESL, NOSInternationalUnder, NOSInternationalGrad, NOSInternationalAss, NOSVNESL, NOSVNUnder, NOSVNGrad, NOSVNAss, NOSStudentFacultyRatioESL, NOSStudentFacultyRatioUnder, NOSStudentFacultyRatioGrad, NOSStudentFacultyRatioAss, CreatedDate, UserId, Portalid)
        'End Sub

        ''------------------------------------------'
        'Public Sub Admis_4Year_UpdateScholarship(ByVal id As Integer, ByVal ScholarshipESL As Boolean, ByVal ScholarshipESLRange As String, ByVal ScholarshipESLRangeVN As String, ByVal ScholarshipUnder As Boolean, ByVal ScholarshipUnderRange As String, ByVal ScholarshipUnderRangeVN As String, ByVal ScholarshipUnderTranfer As Boolean, ByVal ScholarshipUnderTranferRange As String, ByVal ScholarshipUnderTranferRangeVN As String, ByVal ScholarshipGrad As Boolean, ByVal ScholarshipGradRange As String, ByVal ScholarshipGradRangeVN As String, ByVal ScholarshipNote As String, ByVal ScholarshipNoteVN As String, ByVal ScholarshipAss As Boolean, ByVal ScholarshipAssRange As String, ByVal ScholarshipAssRangeVN As String, ByVal OtherfinancialESL As Boolean, ByVal OtherfinancialESLRange As String, ByVal OtherfinancialESLRangeVN As String, ByVal OtherfinancialUnder As Boolean, ByVal OtherfinancialUnderRange As String, ByVal OtherfinancialUnderRangeVN As String, ByVal OtherfinancialUnderTranfer As Boolean, ByVal OtherfinancialUnderTranferRange As String, ByVal OtherfinancialUnderTranferRangeVN As String, ByVal OtherfinancialGrad As Boolean, ByVal OtherfinancialGradRange As String, ByVal OtherfinancialGradRangeVN As String, ByVal OtherfinancialNote As String, ByVal OtherfinancialNoteVN As String, ByVal OtherfinancialAss As Boolean, ByVal OtherfinancialAssRange As String, ByVal OtherfinancialAssRangeVN As String, ByVal CreatedDate As DateTime, ByVal UserId As Integer, ByVal Portalid As Integer)
        '    DataProvider.Instance.Admis_4Year_UpdateScholarship(id, ScholarshipESL, ScholarshipESLRange, ScholarshipESLRangeVN, ScholarshipUnder, ScholarshipUnderRange, ScholarshipUnderRangeVN, ScholarshipUnderTranfer, ScholarshipUnderTranferRange, ScholarshipUnderTranferRangeVN, ScholarshipGrad, ScholarshipGradRange, ScholarshipGradRangeVN, ScholarshipNote, ScholarshipNoteVN, ScholarshipAss, ScholarshipAssRange, ScholarshipAssRangeVN, OtherfinancialESL, OtherfinancialESLRange, OtherfinancialESLRangeVN, OtherfinancialUnder, OtherfinancialUnderRange, OtherfinancialUnderRangeVN, OtherfinancialUnderTranfer, OtherfinancialUnderTranferRange, OtherfinancialUnderTranferRangeVN, OtherfinancialGrad, OtherfinancialGradRange, OtherfinancialGradRangeVN, OtherfinancialNote, OtherfinancialNoteVN, OtherfinancialAss, OtherfinancialAssRange, OtherfinancialAssRangeVN, CreatedDate, UserId, Portalid)
        'End Sub
        ''------------------------------------------'
        'Public Sub Admis_4Year_UpdateTestScore(ByVal id As Integer, ByVal ToeflCBTESL As String, ByVal ToeflCBTUnder As String, ByVal ToeflCBTGrad As String, ByVal ToeflCBTAss As String, ByVal ToefliBTESL As String, ByVal ToefliBTUnder As String, ByVal ToefliBTGrad As String, ByVal ToeflPBTESL As String, ByVal ToeflPBTUnder As String, ByVal ToeflPBTGrad As String, ByVal IELTSESL As String, ByVal IELTSUnder As String, ByVal IELTSGrad As String, ByVal IELTSAss As String, ByVal iTEPESL As String, ByVal iTEPUnder As String, ByVal iTEPGrad As String, ByVal iTEPAss As String, ByVal SAT1ESL As String, ByVal SAT1Under As String, ByVal SAT1Grad As String, ByVal SAT2ESL As String, ByVal SAT2Under As String, ByVal SAT2Grad As String, ByVal GREESL As String, ByVal GREUnder As String, ByVal GREGrad As String, ByVal GMATESL As String, ByVal GMATUnder As String, ByVal GMATGrad As String, ByVal OtherESL As String, ByVal OtherUnder As String, ByVal OtherGrad As String, ByVal OtherAss As String, ByVal CreatedDate As DateTime, ByVal UserId As Integer, ByVal Portalid As Integer)
        '    DataProvider.Instance.Admis_4Year_UpdateTestScore(id, ToeflCBTESL, ToeflCBTUnder, ToeflCBTGrad, ToeflCBTAss, ToefliBTESL, ToefliBTUnder, ToefliBTGrad, ToeflPBTESL, ToeflPBTUnder, ToeflPBTGrad, IELTSESL, IELTSUnder, IELTSGrad, IELTSAss, iTEPESL, iTEPUnder, iTEPGrad, iTEPAss, SAT1ESL, SAT1Under, SAT1Grad, SAT2ESL, SAT2Under, SAT2Grad, GREESL, GREUnder, GREGrad, GMATESL, GMATUnder, GMATGrad, OtherESL, OtherUnder, OtherGrad, OtherAss, CreatedDate, UserId, Portalid)
        'End Sub
        ''------------------------------------------'
        'Public Sub Admis_4Year_UpdateCurrency(ByVal id As Integer, Currency As Integer, ByVal UserId As Integer, ByVal Portalid As Integer)
        '    DataProvider.Instance.Admis_4Year_UpdateCurrency(id, Currency, UserId, Portalid)
        'End Sub
        ''------------------------------------------'
        'Public Sub Admis_4Year_Delete(ByVal id As Integer)
        '    DataProvider.Instance.Admis_4Year_Delete(id)
        'End Sub

        ''------------------------------------------'
        'Public Function Admis_4Year_GetByID(ByVal id As Integer) As Admission4YearInfo
        '    Return CType(CBO.FillObject(DataProvider.Instance.Admis_4Year_GetByID(id), GetType(Admission4YearInfo)), Admission4YearInfo)
        'End Function

        ''------------------------------------------'
        'Public Function Admis_4Year_GetAll() As ArrayList
        '    Return CBO.FillCollection(DataProvider.Instance.Admis_4Year_GetAll(), GetType(Admission4YearInfo))
        'End Function

        '------------------------------------------'
    End Class

End Namespace