'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace NVCMS.Modules.Banner
    
    Partial Public Class edit
        
        '''<summary>
        '''Title control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Title As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtdai control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdai As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtCao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCao As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''filelogo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents filelogo As Global.System.Web.UI.HtmlControls.HtmlInputFile
        
        '''<summary>
        '''dvPreviewlogo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvPreviewlogo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''hpflinkimage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hpflinkimage As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''lbtUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtUpdate As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lbtCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
