'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace NVCMS.Modules.Banner
    
    Partial Public Class List
        
        '''<summary>
        '''lbtAddTop control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtAddTop As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''drgViewData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drgViewData As Global.System.Web.UI.WebControls.Repeater
        
        '''<summary>
        '''lbtAddBottom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtAddBottom As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lbtUpdateOrder control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtUpdateOrder As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
