'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace NVCMS.Modules.Banner
    
    Partial Public Class editbanner
        
        '''<summary>
        '''Title control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Title As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''Descreption control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Descreption As Global.System.Web.UI.HtmlControls.HtmlTextArea
        
        '''<summary>
        '''upbanneried control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upbanneried As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''ddlCategory control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCategory As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txtdai control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdai As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtCao control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCao As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''ddlkieubanner control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlkieubanner As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''filelogo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents filelogo As Global.System.Web.UI.HtmlControls.HtmlInputFile
        
        '''<summary>
        '''dvPreviewlogo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dvPreviewlogo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''hpflinkimage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hpflinkimage As Global.System.Web.UI.WebControls.HiddenField
        
        '''<summary>
        '''txtLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtLink As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtcode control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtcode As Global.System.Web.UI.HtmlControls.HtmlTextArea
        
        '''<summary>
        '''tungay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tungay As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''dengay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dengay As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''thutu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents thutu As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''chkactive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkactive As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
        
        '''<summary>
        '''lbtUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtUpdate As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lbtCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbtCancel As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''imgshowvitri control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgshowvitri As Global.System.Web.UI.WebControls.Image
    End Class
End Namespace
