'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PageSettings
    
    '''<summary>
    '''sitename control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitename As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteweb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteweb As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitediachi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitediachi As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteemail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteemail As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitedienthoai control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitedienthoai As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tenchinhnhanh1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tenchinhnhanh1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitediachi1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitediachi1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteemail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteemail1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitedienthoai1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitedienthoai1 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''tenchinhnhanh2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tenchinhnhanh2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitediachi2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitediachi2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteemail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteemail2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitedienthoai2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitedienthoai2 As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitetomtat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitetomtat As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''sitetag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitetag As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitefacebookpage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitefacebookpage As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteyoutube control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteyoutube As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteInstagram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteInstagram As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteZalo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteZalo As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteTwitter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteTwitter As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteLinkedin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteLinkedin As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitewhatsapp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitewhatsapp As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteSkype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteSkype As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''siteHeaderCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteHeaderCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''siteFooterCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents siteFooterCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPortalId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPortalId As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPortalIdEn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPortalIdEn As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPageTinTuc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPageTinTuc As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPageTinAnh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPageTinAnh As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPageVideo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPageVideo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlPageEvents control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPageEvents As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlfolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlfolder As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''filelogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filelogo As Global.System.Web.UI.HtmlControls.HtmlInputFile
    
    '''<summary>
    '''dvPreviewlogo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvPreviewlogo As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''hpflinkimage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hpflinkimage As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''chkNhanEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNhanEmail As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''EmailLienhe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EmailLienhe As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''sitemaillist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitemaillist As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitecdn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitecdn As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''sitefileserver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sitefileserver As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtgoooglekey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtgoooglekey As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''txtgoooglekeysecret control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtgoooglekeysecret As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''emailsmtp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailsmtp As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''emailtenhienthi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailtenhienthi As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''emailEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailEmail As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''emailmatkhau control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emailmatkhau As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lbtUpdate2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtUpdate2 As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtCancelTop2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtCancelTop2 As Global.System.Web.UI.WebControls.LinkButton
End Class
